"""Initial Schema

Revision ID: 4b8e513a7a50
Revises: 
Create Date: 2026-01-21 00:16:12.823516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8e513a7a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_locations')
    op.drop_table('user_preferences')
    op.drop_table('currency_rates')
    op.drop_table('weather_idioms')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_subs_email'))

    op.drop_table('subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('endpoint', sa.TEXT(), nullable=True),
    sa.Column('p256dh', sa.TEXT(), nullable=True),
    sa.Column('auth', sa.TEXT(), nullable=True),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('lon', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('lon', sa.REAL(), nullable=True),
    sa.Column('subscription_type', sa.TEXT(), server_default=sa.text("'email'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subs_email'), ['email'], unique=1)

    op.create_table('weather_idioms',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('condition', sa.TEXT(), nullable=False),
    sa.Column('idiom', sa.TEXT(), nullable=False),
    sa.Column('language', sa.TEXT(), nullable=False),
    sa.Column('meaning', sa.TEXT(), nullable=True),
    sa.Column('cultural_context', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('base_currency', sa.TEXT(), nullable=False),
    sa.Column('target_currency', sa.TEXT(), nullable=False),
    sa.Column('rate', sa.REAL(), nullable=False),
    sa.Column('last_updated', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('alert_thresholds', sa.TEXT(), nullable=True),
    sa.Column('notification_channels', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('language', sa.TEXT(), server_default=sa.text("'en'"), nullable=True),
    sa.Column('timezone', sa.TEXT(), nullable=True),
    sa.Column('currency', sa.TEXT(), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('temperature_unit', sa.TEXT(), server_default=sa.text("'C'"), nullable=True),
    sa.Column('activities', sa.TEXT(), nullable=True),
    sa.Column('dashboard_config', sa.TEXT(), nullable=True),
    sa.Column('health_config', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorite_locations',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('lon', sa.REAL(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
